version: "3.8"

services:

  db:
    image: mysql
    container_name: Database
    restart: always
    volumes:
      - db-data:/var/lib/mysql
    ports:
      - 3308:3306
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: Design_Patter_db
      MYSQL_USER: design
      MYSQL_PASSWORD: pattern
    networks:
      - dev

  phpmyadmin:
    image: phpmyadmin
    container_name: phpmyadmin
    restart: always
    depends_on:
      - db
    ports:
      - 8083:80
    environment:
      PMA_HOST: db
    networks:
      - dev

  designpattern:
    container_name: DESIGN_PATTERN
    build: .config
    ports:
      - "81:80"
    volumes:
      - ./:/app
    restart: always
    depends_on:
      - db
    networks:
      - dev

networks:
  dev: 

volumes:

  db-data: